# Generated by Django 4.1.4 on 2023-01-10 23:11

from django.db import migrations

def add_allowance_base(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Kid = apps.get_model('imma_chore_app', 'Kid')
    for kid in Kid.objects.all():
        kid.allowance_earned = 0
        kid.save()



class Migration(migrations.Migration):

    dependencies = [
        ('imma_chore_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_allowance_base),
    ]




