# Generated by Django 4.1.4 on 2023-01-06 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imma_chore_app', '0002_chore_kid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chore',
            name='day_of_the_week',
        ),
        migrations.RemoveField(
            model_name='chore',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='kid',
            name='chore',
        ),
        migrations.CreateModel(
            name='Kid_Chore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_the_week', models.DateTimeField()),
                ('is_complete', models.BooleanField(default=False)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imma_chore_app.kid')),
            ],
        ),
    ]
