# Generated by Django 4.1.4 on 2023-01-09 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imma_chore_app', '0004_rename_descriotion_chore_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imma_chore_app.parent'),
        ),
    ]
