# Generated by Django 4.1.4 on 2023-01-09 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imma_chore_app', '0005_alter_kid_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kid_chore',
            name='kid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='imma_chore_app.kid'),
        ),
    ]
