# Generated by Django 4.1.4 on 2023-01-09 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imma_chore_app', '0006_alter_kid_chore_kid'),
    ]

    operations = [
        migrations.AddField(
            model_name='kid_chore',
            name='chore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='imma_chore_app.chore'),
        ),
    ]
